### ISSUE TITLE
Backwards compatibility with vscode versions

### ISSUE THREAD

**Issue by jimfilippou** [DimitrisNL/nord-wave#1]
Got this message while trying to install from extensions tab

```
Unable to install 'dnlytras.nord-wave'; there is no available version compatible with VS Code '1.20.1'.
```

Trying to update to see if the problem persists

**Comment by dimitrisnl** [comment]
Hold the update if possible. Currently working on it.

Patched version will be up within 5 minutes.

**Comment by dimitrisnl** [comment]
Should be good to go!

**Comment by jimfilippou** [comment]
Awesome 🕶
