### ISSUE TITLE
Color scheme of the theme

### ISSUE THREAD

**Issue by dhruv-ahuja** [DimitrisNL/nord-wave#5]
Hi, can you please share the general colour palette for the theme? I really like it and would love to be able to use it in my terminal and elsewhere. 
Thanks!

**Comment by dimitrisnl** [comment]
@dhruv-ahuja It's essentially the Nord theme. You can see the various ports here https://www.nordtheme.com/ports

The main change is having a `#212121` background, to increase contrast.
